anolis: dmaengine: xgene-dma: workaround for compilation errors.
ANBZ: #11232

A compiler internal error was found when compiling allyesconfig with
GCC-12.3.0-2 on x86_64, with the following error message:

  during GIMPLE pass: slp
  drivers/dma/xgene-dma.c: In function 'xgene_dma_prep_xor_desc.isra':
  drivers/dma/xgene-dma.c:414:13: internal compiler error: Segmentation fault
  414 | static void xgene_dma_prep_xor_desc(struct xgene_dma_chan *chan,

After analysis, we identified that the error is an internal issue with GCC.
The problem arises during the compilation of the function
xgene_dma_prep_xor_desc located at drivers/dma/xgene-dma.c:414.
Specifically, the function call xgene_dma_lookup_ext8(desc2, i - 1) within
the expression:
  xgene_dma_set_src_buffer((i == 0) ? &desc1->m1 :
                xgene_dma_lookup_ext8(desc2, i - 1),
                &len, &src[i]);
caused a compiler error. To avoid this issue, the first argument of
xgene_dma_set_src_buffer can be evaluated outside of the function.

No Functional Change!

Signed-off-by: Qinyun Tan <qinyuntan@linux.alibaba.com>
Reviewed-by: Xunlei Pang <xlpang@linux.alibaba.com>
Link: https://gitee.com/anolis/cloud-kernel/pulls/3911