anolis: There need drm-direct.h for loongarch under current kernel version
ANBZ: #11294

Besides, If you do not delete this patch, the following error will be
reported when compiling the kernel image of the loongarch architecture.

./include/linux/dma-direct.h:53:10: fatal error: asm/dma-direct.h:
No such file or directory

Revert "LoongArch: Remove the unused dma-direct.h"

This reverts commit f6758eb7928e8a069c6348010ecd4e635b03aeda.
Reviewed-by: Juxin Gao <gaojuxin@loongson.cn>
Link: https://gitee.com/anolis/cloud-kernel/pulls/3969